# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-09-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210904_1052'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='myuser',
        #     name='image',
        #     field=models.BigIntegerField(default=0),
        # ),
    ]
