# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-09-04 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_myuser_is_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
