# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-09-04 17:31
from __future__ import unicode_literals

from django.db import migrations
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20210904_1643'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', employees.models.UserManager()),
            ],
        ),
    ]
